site_name: "Usumu"
site_url: "https://usumu.io/"
repo_url: "https://github.com/janoszen/usumu/"
markdown_extensions:
  - admonition
  - toc:
      permalink: True
      separator: "-"
theme:
  name: readthedocs
  custom_dir: ./theme/
  include_sidebar: false
  static_templates:
    - .circleci/config.yml
  font: false

  include_search_page: true
  search_index_only: false

  highlightjs: true
  hljs_languages: []

  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
plugins:
  - search
  - macros
nav:
  - 'Home': 'index.md'
  - 'Downloads': 'downloads.md'
  - 'Installation': 'installation.md'
  - 'Configuration': 'configuration.md'
  - 'Cloud providers':
      - 'Amazon Web Services': 'providers/aws.md'
      - 'Azure': 'providers/azure.md'
      - 'DigitalOcean': 'providers/digitalocean.md'
      - 'Exoscale': 'providers/exoscale.md'
  - 'Rules':
      - 'Firewall': 'rules/firewall.md'
      - 'Object Storage': 'rules/objectstorage.md'
  - 'Other features':
      - 'Host discovery': 'other/host-discovery.md'
  - 'Development':
      - 'Contributing to CScanner': 'development/index.md'
      - 'Writing a Provider': 'development/provider.md'
      - 'Writing a Rule': 'development/rule.md'
  - 'About CScanner':
      - 'License': 'about/license.md'
      - 'Imprint': 'about/imprint.md'
      - 'Privacy Policy': 'about/privacy.md'
      - 'Contributors': 'about/contributors.md'
site_favicon: img/favicon.png
extra_css:
  - css/custom.css
copyright: >
  <a href="/about/license/">Copyright &copy; Janos Pasztor and Contributors</a>
  | <a href="/about/imprint/">Imprint</a>
  | <a href="/about/privacy/">Privacy Policy</a>