---
version: 2
jobs: {}
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-branch:
          context: usumu
          filters:
            branches:
              ignore: gh-pages
            tags:
              ignore: /.*/