---
version: 2
defaults: &defaults
  working_directory: /tmp/project
  parallelism: 1
jobs:
  build-branch:
    <<: *defaults
    docker:
    - image: usumu/build
    steps:
      - checkout:
          path: /tmp/project
      - run:
          name: Set Maven version
          command: mvn versions:set -DnewVersion=${CIRCLE_BRANCH}-SNAPSHOT
      - restore_cache:
          key: usumu-{{ checksum "pom.xml" }}
      - run: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: usumu-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: /tmp/project
          paths:
            - "target/*.jar"
      - persist_to_workspace:
          root: /tmp/project
          paths:
          - "Dockerfile"
  build-tag:
    <<: *defaults
    docker:
    - image: usumu/build
    steps:
      - checkout:
          path: /tmp/project
      - run:
          name: Set Maven version
          command: mvn versions:set -DnewVersion=${CIRCLE_TAG}
      - restore_cache:
          key: usumu-{{ checksum "pom.xml" }}
      - run: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: usumu-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: /tmp/project
          paths:
            - "target/*.jar"
      - persist_to_workspace:
          root: /tmp/project
          paths:
          - "Dockerfile"
  deploy-branch:
    <<: *defaults
    docker:
    - image: usumu/build
    steps:
      - attach_workspace:
          at: /tmp/project
      - run: mkdir -p /release
      - run: cp /tmp/project/target/*.jar /release
      - run: mv /release/cli-${CIRCLE_BRANCH}-SNAPSHOT-jar-with-dependencies.jar /release/usumu.jar
      - run: rm /release/cli-${CIRCLE_BRANCH}-SNAPSHOT-javadoc.jar
      - run: rm /release/cli-${CIRCLE_BRANCH}-SNAPSHOT-sources.jar
      - run: rm /release/cli-${CIRCLE_BRANCH}-SNAPSHOT.jar
      - run: ghr -u janoszen -r usumu -recreate -prerelease ${CIRCLE_BRANCH}-SNAPSHOT /release
  deploy-branch-docker:
    <<: *defaults
    machine: true
    steps:
    - attach_workspace:
        at: /tmp/project
    - run:
        command: docker build -t usumu/usumu:${CIRCLE_BRANCH}-SNAPSHOT .
    - run:
        command: docker build -t usumu/usumu:SNAPSHOT .
    - run: |
        echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
    - run: docker push usumu/usumu:${CIRCLE_BRANCH}-SNAPSHOT
    - run: docker push usumu/usumu:SNAPSHOT
  deploy-tag-github:
    <<: *defaults
    docker:
    - image: usumu/build
    steps:
      - add_ssh_keys:
      - attach_workspace:
          at: /tmp/project
      - run: mkdir -p /release
      - run: cp cli/target/*.jar /release
      - run: mv /release/cli-${CIRCLE_TAG}-jar-with-dependencies.jar /release/usumu.jar
      - run: rm /release/cli-${CIRCLE_TAG}-javadoc.jar
      - run: rm /release/cli-${CIRCLE_TAG}-sources.jar
      - run: rm /release/cli-${CIRCLE_TAG}.jar
      - run: ghr -u janoszen -r usumu -recreate ${CIRCLE_TAG} /release
      - run: rm -rf /tmp/project
  deploy-tag-docker:
    <<: *defaults
    machine: true
    steps:
    - attach_workspace:
        at: /tmp/project
    - run:
        command: docker build -t usumu/usumu:${CIRCLE_TAG} .
    - run:
        command: docker build -t usumu/usumu:LATEST .
    - run: |
        echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
    - run: docker push usumu/usumu:${CIRCLE_TAG}
    - run: docker push usumu/usumu:LATEST
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-branch:
          context: build
          filters:
            branches:
              ignore: gh-pages
            tags:
              ignore: /.*/
      - deploy-branch-docker:
          context: build
          requires:
          - build-branch
          filters:
            branches:
              ignore: gh-pages
            tags:
              ignore: /.*/
      - build-tag:
          context: build
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /.*-SNAPSHOT/
      - deploy-tag-github:
          context: build
          requires:
            - build-tag
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /.*-SNAPSHOT/
      - deploy-tag-docker:
          context: build
          requires:
          - build-tag
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /.*-SNAPSHOT/
