package io.usumu.api.common.entity;

public enum ErrorCode {
    ALREADY_EXISTS,
    NOT_FOUND,
    INVALID_VERIFICATION_CODE,
    SUBSCRIPTION_ALREADY_DELETED,
    INVALID_PARAMETERS,
    SUBSCRIPTION_ALREADY_VERIFIED,
    SUBSCRIPTION_DELETED
}
