package io.usumu.api.common.entity;

public enum ErrorCode {
    SUBSCRIPTION_ALREADY_EXISTS,
    SUBSCRIPTION_NOT_FOUND,
    INVALID_VERIFICATION_CODE,
    SUBSCRIPTION_ALREADY_DELETED,
    INVALID_PARAMETERS
}
